package com.easytournament.tournament.calc;

public enum Values {
  HOME_POINTS, AWAY_POINTS, SCORED_HOME_GOALS, RECEIVED_HOME_GOALS, SCORED_AWAY_GOALS, RECEIVED_AWAY_GOALS, 
  RED_CARDS, YELLOW_CARDS, GAMES, HOME_WINS, AWAY_WINS, HOME_DEFEATS, AWAY_DEFEATS, HOME_DRAWS, AWAY_DRAWS;
}
