package com.easytournament.webapp.type;

public enum Sport {
  OTHER, SOCCER, ICEHOCKEY, TENNIS, VOLLEYBALL, BASEBALL, BEACHVOLLEYBALL, HANDBALL, FLOORBALL, CRICKET, TABLETENNIS, GOLF, BADMINTON, RUGBY, SKI, SNOEBOARD, CYCLING, AMERICAN_FOOTBALL, CURLING, STREETHOCKEY, SAILING, SWIMMING, BOWLING
}
